# Generated by Django 4.1.7 on 2023-03-24 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
        ('chat', '0002_rename_owner_function_organization'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Function',
            new_name='Option',
        ),
    ]
