# Generated by Django 4.1.7 on 2023-03-24 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_agentcredentials_agent_agentcredentials_organization_and_more'),
        ('chat', '0003_rename_function_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('variables', models.JSONField(blank=True, help_text='Variables used to generate the template', null=True)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authenticate.agentengine')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.organization')),
            ],
        ),
    ]
