# Generated by Django 4.1.7 on 2023-03-24 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_decisiontemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decisiontemplate',
            name='variables',
        ),
    ]
