# Generated by Django 4.1.7 on 2023-03-24 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_decisiontemplate_variables'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='template',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chat.decisiontemplate'),
        ),
    ]
