# Generated by Django 4.1.7 on 2023-03-24 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_remove_option_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='template',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='chat.decisiontemplate'),
        ),
    ]
